### ISSUE TITLE
Logging Standards

### ISSUE THREAD

**Issue by stephen-bunn** [shawnrice/alfred-bundler#37] opened 2014-08-01 19:12 UTC
We need to define logging standards across all versions of the bundler. 
This includes defining logging levels as well as what information is stored and retrieved.

In the past I have followed a simple format built from Python's logging module.
`[LoggingLevel] <Class, function:line#>....message`

Any ideas on how to improve our logging practice in the bundler?

---
###### Log name

We have only one log.

```
{ab_data_dir}/data/logs/bundler-{major_version}.log
```
###### Log rotation

Each implementation will rotate the logs when necessary. We keep one backup named `<logname>1.log`, and the max filesize for a log is `1MB` or (`decision needed.... 1048576`) bytes.
###### Log levels

```
0 – DEBUG
1 – INFO
2 – WARNING (alias: WARN)
3 – ERROR
4 – CRITICAL (alias: FATAL)
```
###### Syntax

To log file

```
[2014-08-10 02:58:13] [bundler.py:295] [DEBUG] AlfredBundler.py imported
```

To STDERR

```
[02:58:13] [bundler.py:295] [DEBUG] AlfredBundler.py imported
```
##### Meta
- [x] log levels
- [x] log syntax
- [x] logs to have
- [x] log names
- [x] max log size
- [x] mb size
- [x] log rotate functionality
##### Implementation
- [x] Bash
- [x] PHP
- [x] Python
- [x] Ruby

**Comment by shawnrice** [comment] 2014-08-01 19:20
I guess it depends on the purpose of the log. Right now, the PHP logging function just has you specify the name of the log and the line that you want to write prepended with a datetime. Logs are stored in `data/logs/<name>.log` and kept to 500 lines.

So, for the asset log, it just writes something like:

```
Fri Aug 01 14:22:26 EDT 2014 -- INFO: Installed 'utility': 'cocoaDialog' -- version 'default'.
```

We can change the datestamp (as long as it's consistent across all implementations).

PHP also implements a 'composer' log for installing composer assets.

So, it might be better to have what you propose above as part of a general 'error' log, at which point, we could also log anything that would go to STDERR there. Class/function:line# might not be the best way to go, but we do need the equivalent amount of useful debugging information.

**Comment by shawnrice** [comment] 2014-08-01 19:30
So, proposed log levels:
- 0 — INFO
- 1 — WARNING
- 2 — STRICT WARNING
- 3 — RECOVERABLE ERROR
- 4 — ERROR

**Comment by stephen-bunn** [comment] 2014-08-01 19:43
Agreed. 
Will we be going by numerical or named levels? I quite like seeing the level name rather than a number.

**Comment by shawnrice** [comment] 2014-08-01 19:58
The log should _show_ the named level, but we could invoke them with either _just_ numbered level or giving the option of invoking with the named level as well.

**Comment by shawnrice** [comment] 2014-08-02 06:27
Referencing public logs: (#39 ).
For now, I implemented those logging levels in the PHP bundler. Currently, the messages will now read something like:
`[Fri Aug 01 14:22:26 EDT 2014] [INFO]: This is where the user defined message is.`

**Comment by deanishe** [comment] 2014-08-03 13:17
Python has a very solid built-in [logging module](https://docs.python.org/2/howto/logging.html). The output can be tailored to match the output of the other loggers, but we'd be daft to change the API: it's what every Python coder will be expecting. The same applies, imo, to any language that has a built-in or de facto logging library. E.g. we should consider using the `logger` utility in bash.

FWIW, the Python logging lib works like this:

```
logger.debug('message')
logger.info('message')
logger.warning('message')
logger.error('message')
logger.critical('message')
```

The format I usually use is `%H:%M:%S filename:lineno LEVELNAME message`.

I'd also recommend adding a DEBUG level before INFO.

What's the difference between WARNING and STRICT WARNING?

**Comment by stephen-bunn** [comment] 2014-08-03 15:30
Ruby has a [logging class](http://www.ruby-doc.org/stdlib-2.1.2/libdoc/logger/rdoc/Logger.html) very similar to Python's. 

I would suggest removing the STRICT WARNING since these logging utilities don't support it by default. We should keep the language standards for each variant of the bundler. Ruby devs will be expecting us to use this class rather than creating our own.

Supported levels in the Ruby logging class are:

```
DEBUG
INFO
WARN
ERROR
FATAL
UNKNOWN
```

**Comment by shawnrice** [comment] 2014-08-03 17:35
I'm always a fan of the 'unknown' error level. Shouldn't we be able to assign those?

Anyway, I threw in `STRICT WARNING` enough times enough places. From how I've seen it used, it reports more things like deprecated functions and the like in order to push developers to using more modern implementation, but it's not necessary here.

I'm a fan of implementing the Python and Ruby codes. But we should try to make them as uniform as possible across all implementations.

I propose that we implement these levels (0-4, respectively):

```
DEBUG
INFO
WARNING
ERROR
CRITICAL
```

And we should alias `WARNING` with `WARN` and `CRITICAL` with `FATAL`.

As for PHP, I know that there are quite a few logging libraries, and I think that the most standard is [Monolog](https://github.com/Seldaek/monolog) (another alternative is [Analog](https://github.com/jbroadway/analog)), but both seem to be a bit overblown for the Bundler. Unless there are any better suggestions for PHP, then we can just code something that has some parity with Python and Ruby for PHP (and maybe the same for Bash, unless someone has a good idea of a library for that).

**Comment by shawnrice** [comment] 2014-08-04 20:22
I'm thinking that the standard we should use is:
`[YEAR-MONTH-DAY HOUR:MINUTE:SECOND] [filename:lineno] [LEVELNAME] MESSAGE`

Maybe it's just that I like blocking off the units of information to make it easier to pull out the most relevant stuff.

Although, for `ERROR` and `CRITICAL`, we should either
1. Include a traceback to function / method; or
2. Tell them to see the logs where we include more of the traceback there.

Also, I'd rather not worry about rotating logs, so, what should the upper limit on them be? Currently, I'm setting them at 500 lines, but they might need to be bigger, and "lines" might not be the best unit of measurement.

 Thoughts?

**Comment by shawnrice** [comment] 2014-08-04 21:02
@deanishe In your current implementation of the Python bundler, I see something like this:
`2014-08-04 15:54:19,725 bundler.py:289 INFO     Installing bundler ...`

What are the two numbers separated by the comma after the date?

**Comment by stephen-bunn** [comment] 2014-08-04 21:47
Seconds and milliseconds

**Comment by deanishe** [comment] 2014-08-04 22:57
Oops. An oversight on my part.

The format was meant to be `%H:%M:%S`, e.g. `15:54:19`, not the full date and time including milliseconds.

I've updated it correspondingly: I don't see much value in including the date and milliseconds.

It should now look like:

```
15:54:19 bundler.py:289 INFO Installing bundler ...
```

**Comment by shawnrice** [comment] 2014-08-05 00:54
For certain logs (like asset installation), it would probably be helpful to include the date, but for logging that goes to `STDERR`, I agree that the date isn't valuable.

**Comment by shawnrice** [comment] 2014-08-05 06:01
As a preference, can we prepend everything to the logs? I just hate having to scroll through files to find the most recent log information.

**Comment by deanishe** [comment] 2014-08-06 21:45
Prepending to a log is, more or less, just not done. Newest first is  great if you're storing the log in an array within a program, but files just don't really work that way.

Writing to the beginning of a file means having to re-write the rest of it every time a message is logged.

On OSX, you only have to open the log in Console (which is the default app for .log files) and hit the "now" button in the bottom right corner to view and follow the latest entries.

**Comment by shawnrice** [comment] 2014-08-06 21:52
But I hate scrolling almost as much as I hate Time Warner Cable. We can go with those terrible standards that make us waste time scrolling or `tail`ing.

(I also don't like Console).

To be fair, in the PHP bundler, I did load the log as an array and then wrote it back into a file. The nice thing about that method is that it is really easy to prune the logs.

What size cap should we have for these? I don't want to mess with rotating them, but we can if necessary.

**Comment by deanishe** [comment] 2014-08-07 14:08
:smiley: I don't want to be the only project on the planet prepending to their logs!

Python's logging can rotate logs automatically. I've set it to 1MB max size and no old log files.

**Comment by shawnrice** [comment] 2014-08-07 14:43
What happens when they hit 1MB? Are they just flushed entirely?

We need to make sure that all implementations of the bundler are using the same logs and in the same way. After all, the bundler is a backend apparatus, and people will likely be using different implementations of it in various workflows (workflow A uses the bash bundler, workflow b uses the php bundler -- the logs should be in the same place).

So, actually, what logs should we have? 
- Pip (obvs: Python only)
- Gem  (obvs: Ruby only)
- Composer  (obvs: Composer only)
- Generic Asset
- Update
- Error

What else? Anything?

**Comment by deanishe** [comment] 2014-08-09 23:31
> What happens when they hit 1MB? Are they just flushed entirely?

No idea, tbh. But they don't go over 1MB. Maybe I should change it to one older logfile.

Are the logs supposed to be in the same directory or the same log file?

I don't see much benefit in writing different files for update/error/asset etc. It just potentially means hunting around in separate files to figure out what happened.

Either everything in one single log file or one log file per bundler. Seeing as all the other bundlers use the PHP bundler at some point (often via the bash one), a single logfile is probably preferable.

In any case, as long as output is also logged to STDERR, Alfred's debugger should pick it all up.

**Comment by shawnrice** [comment] 2014-08-09 23:35
Okay, changing it over so that there is one old log is probably the best way to go. We'll cap them at 1 mb.

Since the logs now always contain file and line number, then having one log can be just fine because it will be informative enough.

We can implement log rotation in one of three ways, your choice:
1. Build in rotation functionality into each bundler (ugh.... duplication of code).
2. Build in rotation functionality into the update script (so that it's forked / backgrounded).
3. Create a separate `rotate_logs` script that will be called and forked each time to rotate the log if necessary.

The latter two versions shouldn't interfere with anything. I vote for option 3.

**Comment by deanishe** [comment] 2014-08-09 23:48
The Python `logging` module has rotation built in, and I think the Ruby one does, too.

As the other two bundlers are your babies, I guess it's your call.

What's the logfile going to be called, then? `bundler.log`? `taurus.log`? `bundler-{major_version}.log`?

**Comment by shawnrice** [comment] 2014-08-10 00:01
`bundler.log` will do. After all, it'll be in the major version data directory, and then there are more generic instructions to look for the log file of the same name. We can avoid `log.log`, which is my first, least inspired inclination.

Since it's a shared log, the mechanism needs to be consistent, and we have to have the scenarios in which the bundler is either a single or multiple implementations (via different workflows). So, for this issue, we should appeal to the lowest common denominator: Bash (isn't it always?).

Yes/No?

**Comment by deanishe** [comment] 2014-08-10 00:28
`log.log` sucks so bad.

I'd prefer `bundler-{major_version}.log`. It is a duplication of the information in the filepath, but as you tend to spend more time with log files open in Console than staring at them in Finder, I think a slightly more meaningful name is worth having. (This is based on my experience of writing Alfred-Workflow, where I ultimately settled on using `<bundlerid>.log` as the filename.)

> we should appeal to the lowest common denominator: Bash (isn't it always?)

With regard to rotation? I think it's simple enough to do what Python does automatically: check the size of the log file on startup. If it's over 1MB, move it to `<logname>1.log` (replacing any existing file) and start a new log.

Have I missed something?

**Comment by shawnrice** [comment] 2014-08-10 00:35
Okay, `bundler-{major_version}.log` it is. Since it's a variable name, it's easy enough to maintain anyway.

Rotation: I think we're speaking past each other. We'll replicate Python's functionality (delete <logname>1.log, mv <logname>.log <logname>1.log, touch <logname>.log). The question is: who's responsibility is log rotation? A general "cleanup" script that runs sometimes in the background? Or is each bundler responsible for co-maintaining log-rotation (i.e. log-rotation in each bundler). It's baked into Ruby and Python, but I'd have to write something or include a library for PHP and for Bash.

Let's just do this:
1. write a script: `curate_logs.sh` that does said functionality.
2. hook it into `update-wrapper.sh` so that it gets forked the same way (and run each time).

Then, it will rotate the log >= 1MB. The script will be light and even lighten when running in the background. Each bundler should already be invoking the `update-wrapper.sh` script, so there needs to be no change to the bundlers themselves.

**Comment by deanishe** [comment] 2014-08-10 00:57
I think that's simple enough to be a little function in `AlfredBundler.sh`, isn't it?

It gets called when the script is source/run.

I've update the Python bundler/bundlet to use the above-discussed log path and also to use the same logging format.

The only difference is that the date is not logged to STDERR (only the time).

**Comment by shawnrice** [comment] 2014-08-10 01:00
To clarify: the date is logged to the log but not STDERR?

It could be in `AlfredBundler.sh`, (and `AlfredBundler.php`). The only relevant question there is if we want to duplicate the functionality in each one. I'm perfectly ambivalent.

**Comment by deanishe** [comment] 2014-08-10 01:02
Output is logged to both the logfile and STDERR. Messages to the logfile are formatted thusly:

```
[2014-08-10 02:58:13] [bundler.py:295] [DEBUG] AlfredBundler.py imported
```

while the same message is logged to STDERR as:

```
[02:58:13] [bundler.py:295] [DEBUG] AlfredBundler.py imported
```

i.e. without the date.

**Comment by shawnrice** [comment] 2014-08-10 01:05
That makes sense. Each bundler should have the same behavior the same.

**Comment by deanishe** [comment] 2014-08-10 20:47
What's missing then?

The Python wrappers (formerly known as bindings) use a slightly different format, but that will be ignored (I think) as `logging` will already have been initialised by the bundler.

Can we add a checklist to OP?

**Comment by shawnrice** [comment] 2014-08-12 05:05
I hate that I have to ask this, but are we considering a 1 MB to be `1048576` bytes or `1000000` bytes? In other words, are we going with the normal definition or Apple's definition 10.9+?

**Comment by shawnrice** [comment] 2014-08-12 05:10
Updated original post with checklist. Status: one decision left to make. (Let's please go with the standard definition of a MB).

Needs implementation across bundlers. Check them off when they're done.

**Comment by shawnrice** [comment] 2014-08-12 07:27
Integrated and simplified the logging for PHP according to specs with:
- d71266a47c84bfa15da7408552a506853c2883ee
- f2a6d97d8edb742ca9fda7d3271e1b67c4804b9f
- b6a501e37559d08657f437664e85198e4c686b40
- d44e7e4c98a34e57be669ece1bbb530e7c530165

**Comment by deanishe** [comment] 2014-08-12 21:12
Sweet work on the logger there.

**Comment by stephen-bunn** [comment] 2014-08-12 21:20
I'll reformat the wrapper's logging format ASAP.

**Comment by deanishe** [comment] 2014-08-12 22:05
WRT the Python wrappers, the bundler/bundlet use the `bundler` logger, so if you just do, e.g. `log = logging.getLogger('bundler.<util-name>')`, that should log to the already-configured outputs (bundler log file and console).

That's assuming the bundler/bundlet are initialised before the wrappers, which should typically be the case.

Had any thoughts on the best way to expose the wrappers via the bundlet module?

**Comment by shawnrice** [comment] 2014-08-19 18:24
Supported in Ruby now (look in `ruby-dev` branch). I had to reformat the native `logger` module in order to fit with the bundler, but it's working.

I need to refactor the code there to consolidate the functions, but the functionality is there.

Python is up to speed on this, right?

If so, want to check it off and close the issue?

**Comment by deanishe** [comment] 2014-08-19 22:24
AFAIK. The Python bundler is a bit borked ATM. Tests are failing, coverage is lacking and I haven't looked at it in a few days.

May have time tomorrow, but I'm rather busy with `Alfred-Workflow` at the moment, and have a huge contract to translate.

**Comment by shawnrice** [comment] 2014-08-19 22:25
> I'm rather busy with [...] a huge contract to translate.

Damn real work getting in the way of (fun?) non-paid work.

**Comment by deanishe** [comment] 2014-08-19 23:58
Yeah. Why doesn't somebody give me money for _this_ stuff?

**Comment by shawnrice** [comment] 2014-08-20 00:02
We really should find some fun development projects that would also pay us. Or would the pay take the fun out of it?

**Comment by deanishe** [comment] 2014-08-20 08:58
In my experience, it's usually the client who takes the fun out of it :unamused:

**Comment by fractaledmind** [comment] 2014-08-23 16:33
So, a heads up: I've adding logging to the Applescript bundler, but it is somewhat hacky (tho, IMO, much better than nothing; and, IMO, quite good for AS). One particular problem is that it has to manually write to the log file at `alfred.bundler-devel/data/logs/bundler-devel.log`. I wanted one entry per line, so I force a new line at the start of each entry. The `bash` logger does not do this, so when the logs combine, you get something like this:

```
[2014-08-23 12:26:12] [AlfredBundler.php:648] [INFO] Installed 'utility': 'cocoaDialog' -- version 'latest'.

[2014-08-23 12:26:37] [bundler.scpt:icon] [INFO] Icon at `/Users/smargheim/Library/Application Support/Alfred 2/Workflow Data/alfred.bundler-devel/data/assets/icons/octicons/000/arrow` not found...
[2014-08-23 12:27:16] [bundler.scpt:icon] [INFO] Icon at `/Users/smargheim/Library/Application Support/Alfred 2/Workflow Data/alfred.bundler-devel/data/assets/icons/octicons/000/arrow` not found...
[2014-08-23 12:27:16] [bundler.scpt:icon] [INFO] Running shell command: `cd '/Users/smargheim/Documents/DEVELOPMENT/GitHub/alfred-bundler/tests/applescript/'; bash '/Users/smargheim/Library/Application Support/Alfred 2/Workflow Data/alfred.bundler-devel/bundler/bundlets/alfred.bundler.sh' icon octicons arrow 000 true`...[2014-08-23 12:27:17] [icons.sh:120] [ERROR] Error retrieving icon from http://icons.deanishe.net. cURL exited with 22
[2014-08-23 12:27:17] [icons.sh:133] [ERROR] Could not download icon arrow
```

Note the one empty line before the first AS log (that's unavoidable now, but not too costly). Then, not how the first shell log starts directly after the last AS log, without the new line. This needs to be fixed.

**Comment by shawnrice** [comment] 2014-08-23 17:26
The Bash bundler throws everything on its own newline, so the problem isn't there, but it's in the interaction between the AS frontend and Bash backend.

Instead of forcing the newline at the front, why not force the newline at the end? So instead of `\nThis is the message`, you'd have `This is the message\n`.

**Comment by fractaledmind** [comment] 2014-08-23 17:32
Boom. Done. Good call. Short sentences.

**Closed as completed** 2014-09-05 20:47 UTC
Labels: Python, PHP, Ruby, Bash, Feature, Needs Discussion
